// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace DocAnalyzerDataHandler
{
    public partial class DocAnalyzerContext : DbContext
    {
        public DocAnalyzerContext()
        {
        }

        public DocAnalyzerContext(DbContextOptions<DocAnalyzerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Usercredential> Usercredential { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Spanish_Costa Rica.1252");

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("employee_pkey");
            });

            modelBuilder.Entity<Usercredential>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("usercredential_pkey");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}